import fetch from "node-fetch";

/**
 * Generates a website structure and code using OpenRouter.
 * Optimized for React-based website generation.
 */
export const generateResponse = async (messages) => {
  // 1. Get and Clean API Key
  const rawKey = process.env.OPENROUTER_API_KEY;
  
  if (!rawKey) {
    console.error("❌ ERROR: OPENROUTER_API_KEY is missing in .env");
    throw new Error("Server configuration error: Missing API Key");
  }

  // Remove quotes or spaces that often cause the 401 error
  const API_KEY = rawKey.replace(/['"]+/g, '').trim();

  // 2. Prepare Payload
  const formattedMessages = Array.isArray(messages) 
    ? messages 
    : [{ role: "user", content: messages }];

  try {
    console.log("🚀 Initiating AI Generation...");

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${API_KEY}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://gensite-ai.onrender.com", // Required by some OpenRouter models
        "X-Title": "GenSite AI Builder",
      },
      body: JSON.stringify({
        model: "openai/gpt-4o-mini", // Best balance of speed/cost for code
        messages: formattedMessages,
        temperature: 0.2, // Low temperature for consistent code structure
        response_format: { type: "json_object" } // Forces AI to return valid JSON
      }),
    });

    // 3. Handle Non-OK Responses
    if (!response.ok) {
      const errorText = await response.text();
      let errorMessage = "AI Service Error";
      
      try {
        const errorJson = JSON.parse(errorText);
        errorMessage = errorJson.error?.message || errorMessage;
      } catch (e) {
        errorMessage = errorText;
      }

      console.error(`❌ OpenRouter Error (${response.status}):`, errorMessage);
      throw new Error(errorMessage);
    }

    const data = await response.json();

    // 4. Validate and Extract Content
    const content = data?.choices?.[0]?.message?.content;

    if (!content) {
      console.error("⚠️ AI returned an empty response choices array.");
      throw new Error("No content generated by AI");
    }

    console.log("✅ Website Generated Successfully");
    return content;

  } catch (error) {
    console.error("❌ generateResponse Error:", error.message);
    throw error;
  }
};